clc; clear; close all;

%% =========================
%  Selected cases for visualization
%  LQAZO is better than both QZO and LoQZO in these cases
%% =========================
datasets = { ...
    'SST2\newline(W8A8)', ...
    'RTE\newline(W8A8)', ...
    'WSC\newline(W8A8)', ...
    'MultiRC\newline(W4A4)', ...
    'COPA\newline(W4A8)'};

QZO    = [61.20, 56.64, 47.11, 53.60, 54.00];
LoQZO  = [61.20, 55.46, 48.07, 51.40, 56.00];
LQAZO  = [63.00, 59.37, 50.96, 57.00, 57.00];

best_baseline = max([QZO; LoQZO], [], 1);
improvement = LQAZO - best_baseline;

%% =========================
%  Color palette
%% =========================
color_qzo   = [0.16 0.36 0.55];   % deep blue
color_loqzo = [0.16 0.58 0.50];   % teal green
color_lqazo = [0.88 0.43 0.16];   % warm orange
color_gain  = [0.78 0.24 0.18];   % red-orange

%% ============================================================
%  Figure 1: Grouped bar chart for absolute performance
%% ============================================================
fig1 = figure('Position', [120, 120, 980, 500], 'Color', 'w');

Y = [QZO; LoQZO; LQAZO]';
b = bar(Y, 'grouped', 'BarWidth', 0.78);
hold on;
grid on;
box on;

% Bar colors
b(1).FaceColor = color_qzo;
b(2).FaceColor = color_loqzo;
b(3).FaceColor = color_lqazo;

b(1).EdgeColor = 'none';
b(2).EdgeColor = 'none';
b(3).EdgeColor = 'none';

% Axis settings
set(gca, ...
    'XTick', 1:length(datasets), ...
    'XTickLabel', datasets, ...
    'TickLabelInterpreter', 'tex', ...
    'FontSize', 12, ...
    'LineWidth', 1.1, ...
    'FontName', 'Times New Roman', ...
    'TickDir', 'out', ...
    'GridAlpha', 0.18);

% 改成不倾斜
xtickangle(0);

ylabel('Performance', ...
    'FontSize', 13, ...
    'FontName', 'Times New Roman');

% title('Selected Ablation Results on OPT-1.3B', ...
%     'FontSize', 15, ...
%     'FontWeight', 'bold', ...
%     'FontName', 'Times New Roman');

legend({'QZO-(LQAZO/LoQZO)', 'LoQZO-(LQAZO/QZO)', 'LQAZO'}, ...
    'Location', 'northoutside', ...
    'Orientation', 'horizontal', ...
    'FontSize', 11, ...
    'Box', 'off', ...
    'FontName', 'Times New Roman');

% Y-axis range
ymin = floor(min([QZO, LoQZO, LQAZO]) - 3);
ymax = ceil(max([QZO, LoQZO, LQAZO]) + 6);
ylim([ymin ymax]);

% Add numeric labels
for k = 1:length(b)
    xtips = b(k).XEndPoints;
    ytips = b(k).YEndPoints;
    labels = compose('%.2f', ytips);
    text(xtips, ytips + 0.30, labels, ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'bottom', ...
        'FontSize', 10, ...
        'FontName', 'Times New Roman');
end

% Add gain labels above LQAZO bars
xtips = b(3).XEndPoints;
for i = 1:length(improvement)
    text(xtips(i), LQAZO(i) + 1.35, sprintf('\\Delta=+%.2f', improvement(i)), ...
        'HorizontalAlignment', 'center', ...
        'FontSize', 10.5, ...
        'FontWeight', 'bold', ...
        'Color', color_gain, ...
        'FontName', 'Times New Roman');
end

% Save Figure 1
exportgraphics(fig1, 'lqazo_selected_ablation_bars.png', 'Resolution', 300);
exportgraphics(fig1, 'lqazo_selected_ablation_bars.pdf', 'ContentType', 'vector');


%% ============================================================
%  Figure 2: Horizontal gain chart
%% ============================================================
fig2 = figure('Position', [160, 160, 760, 500], 'Color', 'w');

barh(improvement, 0.55, ...
    'FaceColor', color_gain, ...
    'EdgeColor', 'none');
hold on;
grid on;
box on;

xline(0, 'k-', 'LineWidth', 1.0);

set(gca, ...
    'YTick', 1:length(datasets), ...
    'YTickLabel', datasets, ...
    'TickLabelInterpreter', 'tex', ...
    'YDir', 'reverse', ...
    'FontSize', 12, ...
    'LineWidth', 1.1, ...
    'FontName', 'Times New Roman', ...
    'TickDir', 'out', ...
    'GridAlpha', 0.18);

xlabel('\Delta over best baseline', ...
    'FontSize', 13, ...
    'FontName', 'Times New Roman');

% title('LQAZO Gain over the Stronger Baseline', ...
%     'FontSize', 15, ...
%     'FontWeight', 'bold', ...
%     'FontName', 'Times New Roman');

xlim([0, max(improvement) + 0.9]);

% Add value labels
for i = 1:length(improvement)
    text(improvement(i) + 0.06, i, sprintf('+%.2f', improvement(i)), ...
        'HorizontalAlignment', 'left', ...
        'VerticalAlignment', 'middle', ...
        'FontSize', 12, ...
        'FontWeight', 'bold', ...
        'Color', color_gain, ...
        'FontName', 'Times New Roman');
end

% Save Figure 2
exportgraphics(fig2, 'lqazo_selected_ablation_gain.png', 'Resolution', 300);
exportgraphics(fig2, 'lqazo_selected_ablation_gain.pdf', 'ContentType', 'vector');